name: Jekyll Deploy
on:
  push:
    branches: [master]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Create icons
        run: |
          add-apt-repository universe
          add-apt-repository ppa:inkscape.dev/stable
          apt-get update
          apt install inkscape
          python create_icons.py
      - name: Build & Deploy to GitHub Pages
        uses: helaili/jekyll-action@2.0.4
        with:
          jekyll_src: '.'
          gem_src: '.'
          target_branch: 'gh-pages'
        env:
          JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
